### PR TITLE
Update XulRunner version to 1.9.1.19 so bootstrap script can run successfully

### PR DESCRIPTION
**Pull request by jrichard**
Update XulRunner version to 1.9.1.19 so bootstrap script can run successfully.  1.9.1.18 is no longer available.  Didn't try 1.9.2.x due to past commit comments.

### CODE REVIEW

**Comment by lthill** [comment]
I am running the mesabe virtual machine which has XulRunner 1.9.2.18. I need to downgrade to 1.9.1.19 but this is very complicated with all the dependencies within Gnome. Any suggestions on where to start with getting a machine ready for running ssu?

**Comment by jrichard** [comment]
Sorry, I'm not using the VM.  I'm unsure how the VM was created, but if there's a bootstrap script with it you could try substituting the different XulRunner version and create a new image with the updated dependency.

**Comment by lthill** [comment]
Thanks. Will try.

Learning.

**Comment by lthill** [comment]
Sweet. Got it working on Debian.

**Comment by eventualbuddha** [comment]
Is this still an issue?

**Comment by lthill** [comment]
Does not seem to be. Appears to work fine in Ubuntu 10.04 with 1.9.2.8 and in Debian Squeeze with version 1.9.1.16

**Comment by eventualbuddha** [comment]
Cool, thanks.

**Pull request closed without merging**
